FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

# System deps
RUN apt-get update && apt-get install -y \
    python \
    python-pip \
    python3 \
    python3-pip \
    python3-venv \
    ffmpeg \
    libsndfile1 \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy requirements first (better caching)
COPY requirements.txt .

RUN python3 -m pip install -U pip setuptools wheel

RUN python3 -m pip install torch==2.8.0 torchaudio==2.8.0 \
    --extra-index-url https://download.pytorch.org/whl/cu121

RUN python3 -m pip install --no-cache-dir qwen-asr

# Upgrade pip + install deps
RUN python3 -m pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY . .

CMD ["python3", "-m", "src.start", "--host", "0.0.0.0", "--port", "8000"]