FROM vllm/vllm-openai:v0.16.0

ENV DEBIAN_FRONTEND=noninteractive

# System deps
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv \
    ffmpeg \
    libsndfile1 \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install -U qwen-asr[vllm]

RUN python3 -m pip install -U --ignore-installed -c /tmp/constraints.txt qwen-asr


# Copy requirements first (better caching)
COPY requirements.txt .

# Upgrade pip + install deps
RUN python3 -m pip install --no-cache-dir --ignore-installed -c /tmp/constraints.txt -r requirements.txt

# Copy app code
COPY . .

CMD ["python3", "-m", "src.start", "--host", "0.0.0.0", "--port", "8000"]