FROM qwenllm/qwen3-asr

ENV DEBIAN_FRONTEND=noninteractive

# System deps
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsndfile1 \
    git \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN pip install vllm==0.6.0

RUN pip install torch==2.8.0 torchaudio==2.8.0


# Copy requirements first (better caching)
COPY requirements.txt .

# Upgrade pip + install deps
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY . .

CMD ["python", "main.py"]